@host = http://localhost:8080
###

POST {{host}}/auth/signUp
Content-Type: application/json

{
  "Avatar": "sampleavatarurl",
  "Username": "bobisgreat",
  "Password": "bobisawesome",
  "Courses": ["5dcad16b2e493cd969d8a1b3"],
  "Level": 3
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
  "Username": "bobisgreat",
  "Password": "bobisawesome"
}