@host = http://localhost:8000
###

GET {{host}}/courses

###


# @name CreateCourse
POST {{host}}/courses
Content-Type: application/json

{
  "Language": "en",
  "NextMotivator": 2,
  "Score": 0,
  "Logs": []
}

###

PATCH {{host}}/courses/5dcad16b2e493cd969d8a1b3
Content-Type: application/json

{
  "Set": {
    "score": 34
  },
  "Push": {
    "logs": {
      "phraseid": "5dc87a942a7dfb11d2f8e310",
      "timestamp": 3,
      "attempts": 1
    }
  }
}