@host = http://localhost:8080
###

GET {{host}}/courses
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI1ZGUxNTcwYjg2ZGNiNDkwNjE0ZDVkZjEifQ.t_LP_wZp9I6gmo6pLgrmJctgsiy9o5vgxbXk2zHe6h0

###


# @name Random
GET {{host}}/phrases/random/en
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI1ZGUxNTcwYjg2ZGNiNDkwNjE0ZDVkZjEifQ.t_LP_wZp9I6gmo6pLgrmJctgsiy9o5vgxbXk2zHe6h0

###

# @name TranslateAPI
GET https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20191218T231531Z.5ba725d98c6e8cdc.09fa6069579b6c4324f33f569e38e7be41454586&text=sleep&lang=en-ar

###

# @name SpeechAPI
GET https://translate.google.com.vn/translate_tts?ie=UTF-8&q=how+are+you&tl=en&client=tw-ob

### github.com/mozillazg/go-unidecode

DELETE {{host}}/phrases/5de2e8db432c1c5241ba8c9d
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI1ZGUxNTcwYjg2ZGNiNDkwNjE0ZDVkZjEifQ.t_LP_wZp9I6gmo6pLgrmJctgsiy9o5vgxbXk2zHe6h0
###